/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DnlApi) {
      root.DnlApi = {};
    }
    root.DnlApi.CarrierGet = factory(root.DnlApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CarrierGet model module.
   * @module model/CarrierGet
   * @version 1.2.10
   */

  /**
   * Constructs a new <code>CarrierGet</code>.
   * @alias module:model/CarrierGet
   * @class
   */
  var exports = function() {
    var _this = this;










































  };

  /**
   * Constructs a <code>CarrierGet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarrierGet} obj Optional instance to populate.
   * @return {module:model/CarrierGet} The populated <code>CarrierGet</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('client_id')) {
        obj['client_id'] = ApiClient.convertToType(data['client_id'], 'Number');
      }
      if (data.hasOwnProperty('is_unlimited')) {
        obj['is_unlimited'] = ApiClient.convertToType(data['is_unlimited'], 'Boolean');
      }
      if (data.hasOwnProperty('cps_limit')) {
        obj['cps_limit'] = ApiClient.convertToType(data['cps_limit'], 'Number');
      }
      if (data.hasOwnProperty('company')) {
        obj['company'] = ApiClient.convertToType(data['company'], 'String');
      }
      if (data.hasOwnProperty('test_credit')) {
        obj['test_credit'] = ApiClient.convertToType(data['test_credit'], 'Number');
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
      }
      if (data.hasOwnProperty('profit_type')) {
        obj['profit_type'] = ApiClient.convertToType(data['profit_type'], 'String');
      }
      if (data.hasOwnProperty('egress_count')) {
        obj['egress_count'] = ApiClient.convertToType(data['egress_count'], 'Number');
      }
      if (data.hasOwnProperty('report_frequency')) {
        obj['report_frequency'] = ApiClient.convertToType(data['report_frequency'], 'Number');
      }
      if (data.hasOwnProperty('carrier_template_id')) {
        obj['carrier_template_id'] = ApiClient.convertToType(data['carrier_template_id'], 'Number');
      }
      if (data.hasOwnProperty('daily_usage_summary')) {
        obj['daily_usage_summary'] = ApiClient.convertToType(data['daily_usage_summary'], 'Boolean');
      }
      if (data.hasOwnProperty('update_by')) {
        obj['update_by'] = ApiClient.convertToType(data['update_by'], 'String');
      }
      if (data.hasOwnProperty('daily_usage_group_by')) {
        obj['daily_usage_group_by'] = ApiClient.convertToType(data['daily_usage_group_by'], 'String');
      }
      if (data.hasOwnProperty('ingress_count')) {
        obj['ingress_count'] = ApiClient.convertToType(data['ingress_count'], 'Number');
      }
      if (data.hasOwnProperty('billing_email')) {
        obj['billing_email'] = ApiClient.convertToType(data['billing_email'], 'String');
      }
      if (data.hasOwnProperty('short_call_duration')) {
        obj['short_call_duration'] = ApiClient.convertToType(data['short_call_duration'], 'Number');
      }
      if (data.hasOwnProperty('short_call_charge_exceed_only')) {
        obj['short_call_charge_exceed_only'] = ApiClient.convertToType(data['short_call_charge_exceed_only'], 'Number');
      }
      if (data.hasOwnProperty('one_time_report_time')) {
        obj['one_time_report_time'] = ApiClient.convertToType(data['one_time_report_time'], 'Number');
      }
      if (data.hasOwnProperty('actual_balance')) {
        obj['actual_balance'] = ApiClient.convertToType(data['actual_balance'], 'Number');
      }
      if (data.hasOwnProperty('noc_email')) {
        obj['noc_email'] = ApiClient.convertToType(data['noc_email'], 'String');
      }
      if (data.hasOwnProperty('credit_limit')) {
        obj['credit_limit'] = ApiClient.convertToType(data['credit_limit'], 'Number');
      }
      if (data.hasOwnProperty('mutual_balance')) {
        obj['mutual_balance'] = ApiClient.convertToType(data['mutual_balance'], 'Number');
      }
      if (data.hasOwnProperty('rate_email')) {
        obj['rate_email'] = ApiClient.convertToType(data['rate_email'], 'String');
      }
      if (data.hasOwnProperty('ingress_count_sql')) {
        obj['ingress_count_sql'] = ApiClient.convertToType(data['ingress_count_sql'], 'Number');
      }
      if (data.hasOwnProperty('daily_usage_on_non_zero')) {
        obj['daily_usage_on_non_zero'] = ApiClient.convertToType(data['daily_usage_on_non_zero'], 'Boolean');
      }
      if (data.hasOwnProperty('trunk_update_alert')) {
        obj['trunk_update_alert'] = ApiClient.convertToType(data['trunk_update_alert'], 'Boolean');
      }
      if (data.hasOwnProperty('short_call_percent')) {
        obj['short_call_percent'] = ApiClient.convertToType(data['short_call_percent'], 'Number');
      }
      if (data.hasOwnProperty('update_at')) {
        obj['update_at'] = ApiClient.convertToType(data['update_at'], 'Date');
      }
      if (data.hasOwnProperty('is_prepay')) {
        obj['is_prepay'] = ApiClient.convertToType(data['is_prepay'], 'Boolean');
      }
      if (data.hasOwnProperty('short_call_charge')) {
        obj['short_call_charge'] = ApiClient.convertToType(data['short_call_charge'], 'Number');
      }
      if (data.hasOwnProperty('is_active')) {
        obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
      }
      if (data.hasOwnProperty('currency_name')) {
        obj['currency_name'] = ApiClient.convertToType(data['currency_name'], 'String');
      }
      if (data.hasOwnProperty('main_email')) {
        obj['main_email'] = ApiClient.convertToType(data['main_email'], 'String');
      }
      if (data.hasOwnProperty('account_detail')) {
        obj['account_detail'] = ApiClient.convertToType(data['account_detail'], 'String');
      }
      if (data.hasOwnProperty('call_limit')) {
        obj['call_limit'] = ApiClient.convertToType(data['call_limit'], 'Number');
      }
      if (data.hasOwnProperty('low_balance_alert')) {
        obj['low_balance_alert'] = ApiClient.convertToType(data['low_balance_alert'], 'Boolean');
      }
      if (data.hasOwnProperty('auto_invoice_type')) {
        obj['auto_invoice_type'] = ApiClient.convertToType(data['auto_invoice_type'], 'String');
      }
      if (data.hasOwnProperty('daily_balance_summary')) {
        obj['daily_balance_summary'] = ApiClient.convertToType(data['daily_balance_summary'], 'Boolean');
      }
      if (data.hasOwnProperty('daily_cdr_delivery')) {
        obj['daily_cdr_delivery'] = ApiClient.convertToType(data['daily_cdr_delivery'], 'Boolean');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} client_id
   */
  exports.prototype['client_id'] = undefined;
  /**
   * @member {Boolean} is_unlimited
   */
  exports.prototype['is_unlimited'] = undefined;
  /**
   * @member {Number} cps_limit
   */
  exports.prototype['cps_limit'] = undefined;
  /**
   * @member {String} company
   */
  exports.prototype['company'] = undefined;
  /**
   * @member {Number} test_credit
   */
  exports.prototype['test_credit'] = undefined;
  /**
   * @member {String} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * @member {module:model/CarrierGet.ProfitTypeEnum} profit_type
   * @default 'percentage'
   */
  exports.prototype['profit_type'] = 'percentage';
  /**
   * @member {Number} egress_count
   */
  exports.prototype['egress_count'] = undefined;
  /**
   * @member {Number} report_frequency
   */
  exports.prototype['report_frequency'] = undefined;
  /**
   * @member {Number} carrier_template_id
   */
  exports.prototype['carrier_template_id'] = undefined;
  /**
   * @member {Boolean} daily_usage_summary
   */
  exports.prototype['daily_usage_summary'] = undefined;
  /**
   * @member {String} update_by
   */
  exports.prototype['update_by'] = undefined;
  /**
   * @member {module:model/CarrierGet.DailyUsageGroupByEnum} daily_usage_group_by
   * @default 'By Country'
   */
  exports.prototype['daily_usage_group_by'] = 'By Country';
  /**
   * @member {Number} ingress_count
   */
  exports.prototype['ingress_count'] = undefined;
  /**
   * @member {String} billing_email
   */
  exports.prototype['billing_email'] = undefined;
  /**
   * @member {Number} short_call_duration
   */
  exports.prototype['short_call_duration'] = undefined;
  /**
   * @member {Number} short_call_charge_exceed_only
   */
  exports.prototype['short_call_charge_exceed_only'] = undefined;
  /**
   * @member {Number} one_time_report_time
   */
  exports.prototype['one_time_report_time'] = undefined;
  /**
   * @member {Number} actual_balance
   */
  exports.prototype['actual_balance'] = undefined;
  /**
   * @member {String} noc_email
   */
  exports.prototype['noc_email'] = undefined;
  /**
   * @member {Number} credit_limit
   */
  exports.prototype['credit_limit'] = undefined;
  /**
   * @member {Number} mutual_balance
   */
  exports.prototype['mutual_balance'] = undefined;
  /**
   * @member {String} rate_email
   */
  exports.prototype['rate_email'] = undefined;
  /**
   * @member {Number} ingress_count_sql
   */
  exports.prototype['ingress_count_sql'] = undefined;
  /**
   * @member {Boolean} daily_usage_on_non_zero
   */
  exports.prototype['daily_usage_on_non_zero'] = undefined;
  /**
   * @member {Boolean} trunk_update_alert
   */
  exports.prototype['trunk_update_alert'] = undefined;
  /**
   * @member {Number} short_call_percent
   */
  exports.prototype['short_call_percent'] = undefined;
  /**
   * @member {Date} update_at
   */
  exports.prototype['update_at'] = undefined;
  /**
   * @member {Boolean} is_prepay
   */
  exports.prototype['is_prepay'] = undefined;
  /**
   * @member {Number} short_call_charge
   */
  exports.prototype['short_call_charge'] = undefined;
  /**
   * @member {Boolean} is_active
   */
  exports.prototype['is_active'] = undefined;
  /**
   * @member {String} currency_name
   */
  exports.prototype['currency_name'] = undefined;
  /**
   * @member {String} main_email
   */
  exports.prototype['main_email'] = undefined;
  /**
   * @member {String} account_detail
   */
  exports.prototype['account_detail'] = undefined;
  /**
   * @member {Number} call_limit
   */
  exports.prototype['call_limit'] = undefined;
  /**
   * @member {Boolean} low_balance_alert
   */
  exports.prototype['low_balance_alert'] = undefined;
  /**
   * @member {module:model/CarrierGet.AutoInvoiceTypeEnum} auto_invoice_type
   * @default 'buy'
   */
  exports.prototype['auto_invoice_type'] = 'buy';
  /**
   * @member {Boolean} daily_balance_summary
   */
  exports.prototype['daily_balance_summary'] = undefined;
  /**
   * @member {Boolean} daily_cdr_delivery
   */
  exports.prototype['daily_cdr_delivery'] = undefined;
  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;


  /**
   * Allowed values for the <code>profit_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ProfitTypeEnum = {
    /**
     * value: "value"
     * @const
     */
    "value": "value",
    /**
     * value: "percentage"
     * @const
     */
    "percentage": "percentage"  };

  /**
   * Allowed values for the <code>daily_usage_group_by</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DailyUsageGroupByEnum = {
    /**
     * value: "By Country"
     * @const
     */
    "Country": "By Country",
    /**
     * value: "By Code Name"
     * @const
     */
    "Code Name": "By Code Name",
    /**
     * value: "By Code"
     * @const
     */
    "Code": "By Code"  };

  /**
   * Allowed values for the <code>auto_invoice_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AutoInvoiceTypeEnum = {
    /**
     * value: "both"
     * @const
     */
    "both": "both",
    /**
     * value: "buy"
     * @const
     */
    "buy": "buy",
    /**
     * value: "sell"
     * @const
     */
    "sell": "sell"  };


  return exports;
}));


