/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DnlApi) {
      root.DnlApi = {};
    }
    root.DnlApi.ImportExportLogsImport = factory(root.DnlApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ImportExportLogsImport model module.
   * @module model/ImportExportLogsImport
   * @version 1.2.10
   */

  /**
   * Constructs a new <code>ImportExportLogsImport</code>.
   * @alias module:model/ImportExportLogsImport
   * @class
   */
  var exports = function() {
    var _this = this;















  };

  /**
   * Constructs a <code>ImportExportLogsImport</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImportExportLogsImport} obj Optional instance to populate.
   * @return {module:model/ImportExportLogsImport} The populated <code>ImportExportLogsImport</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('records_succ')) {
        obj['records_succ'] = ApiClient.convertToType(data['records_succ'], 'Number');
      }
      if (data.hasOwnProperty('user_name')) {
        obj['user_name'] = ApiClient.convertToType(data['user_name'], 'String');
      }
      if (data.hasOwnProperty('db_error_file_path')) {
        obj['db_error_file_path'] = ApiClient.convertToType(data['db_error_file_path'], 'String');
      }
      if (data.hasOwnProperty('obj')) {
        obj['obj'] = ApiClient.convertToType(data['obj'], 'String');
      }
      if (data.hasOwnProperty('method')) {
        obj['method'] = ApiClient.convertToType(data['method'], 'String');
      }
      if (data.hasOwnProperty('upload_file')) {
        obj['upload_file'] = ApiClient.convertToType(data['upload_file'], 'String');
      }
      if (data.hasOwnProperty('file_name')) {
        obj['file_name'] = ApiClient.convertToType(data['file_name'], 'String');
      }
      if (data.hasOwnProperty('finished_time')) {
        obj['finished_time'] = ApiClient.convertToType(data['finished_time'], 'Date');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('records_fail')) {
        obj['records_fail'] = ApiClient.convertToType(data['records_fail'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('error_file_path')) {
        obj['error_file_path'] = ApiClient.convertToType(data['error_file_path'], 'String');
      }
      if (data.hasOwnProperty('upload_time')) {
        obj['upload_time'] = ApiClient.convertToType(data['upload_time'], 'Date');
      }
      if (data.hasOwnProperty('records_dup')) {
        obj['records_dup'] = ApiClient.convertToType(data['records_dup'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} records_succ
   */
  exports.prototype['records_succ'] = undefined;
  /**
   * @member {String} user_name
   */
  exports.prototype['user_name'] = undefined;
  /**
   * @member {String} db_error_file_path
   */
  exports.prototype['db_error_file_path'] = undefined;
  /**
   * @member {String} obj
   */
  exports.prototype['obj'] = undefined;
  /**
   * @member {String} method
   */
  exports.prototype['method'] = undefined;
  /**
   * @member {String} upload_file
   */
  exports.prototype['upload_file'] = undefined;
  /**
   * @member {String} file_name
   */
  exports.prototype['file_name'] = undefined;
  /**
   * @member {Date} finished_time
   */
  exports.prototype['finished_time'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} records_fail
   */
  exports.prototype['records_fail'] = undefined;
  /**
   * @member {module:model/ImportExportLogsImport.StatusEnum} status
   * @default 'success'
   */
  exports.prototype['status'] = 'success';
  /**
   * @member {String} error_file_path
   */
  exports.prototype['error_file_path'] = undefined;
  /**
   * @member {Date} upload_time
   */
  exports.prototype['upload_time'] = undefined;
  /**
   * @member {Number} records_dup
   */
  exports.prototype['records_dup'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "fail"
     * @const
     */
    "fail": "fail",
    /**
     * value: "success"
     * @const
     */
    "success": "success",
    /**
     * value: "undefined"
     * @const
     */
    "undefined": "undefined"  };


  return exports;
}));


