/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DnlApi) {
      root.DnlApi = {};
    }
    root.DnlApi.RateTableEmpty = factory(root.DnlApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RateTableEmpty model module.
   * @module model/RateTableEmpty
   * @version 1.2.10
   */

  /**
   * Constructs a new <code>RateTableEmpty</code>.
   * @alias module:model/RateTableEmpty
   * @class
   * @param name {String} 
   */
  var exports = function(name) {
    var _this = this;


    _this['name'] = name;
















  };

  /**
   * Constructs a <code>RateTableEmpty</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RateTableEmpty} obj Optional instance to populate.
   * @return {module:model/RateTableEmpty} The populated <code>RateTableEmpty</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('resources')) {
        obj['resources'] = ApiClient.convertToType(data['resources'], ['String']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('prefix_max_length')) {
        obj['prefix_max_length'] = ApiClient.convertToType(data['prefix_max_length'], 'Number');
      }
      if (data.hasOwnProperty('jur_type')) {
        obj['jur_type'] = ApiClient.convertToType(data['jur_type'], 'Number');
      }
      if (data.hasOwnProperty('code_deck_id')) {
        obj['code_deck_id'] = ApiClient.convertToType(data['code_deck_id'], 'Number');
      }
      if (data.hasOwnProperty('rate_type')) {
        obj['rate_type'] = ApiClient.convertToType(data['rate_type'], 'Number');
      }
      if (data.hasOwnProperty('currency_id')) {
        obj['currency_id'] = ApiClient.convertToType(data['currency_id'], 'Number');
      }
      if (data.hasOwnProperty('noprefix_min_length')) {
        obj['noprefix_min_length'] = ApiClient.convertToType(data['noprefix_min_length'], 'Number');
      }
      if (data.hasOwnProperty('billing_method')) {
        obj['billing_method'] = ApiClient.convertToType(data['billing_method'], 'String');
      }
      if (data.hasOwnProperty('lnp_dipping_rate')) {
        obj['lnp_dipping_rate'] = ApiClient.convertToType(data['lnp_dipping_rate'], 'Number');
      }
      if (data.hasOwnProperty('rate_type_name')) {
        obj['rate_type_name'] = ApiClient.convertToType(data['rate_type_name'], 'String');
      }
      if (data.hasOwnProperty('noprefix_max_length')) {
        obj['noprefix_max_length'] = ApiClient.convertToType(data['noprefix_max_length'], 'Number');
      }
      if (data.hasOwnProperty('jurisdiction_country_id')) {
        obj['jurisdiction_country_id'] = ApiClient.convertToType(data['jurisdiction_country_id'], 'Number');
      }
      if (data.hasOwnProperty('is_virtual')) {
        obj['is_virtual'] = ApiClient.convertToType(data['is_virtual'], 'Boolean');
      }
      if (data.hasOwnProperty('prefix_min_length')) {
        obj['prefix_min_length'] = ApiClient.convertToType(data['prefix_min_length'], 'Number');
      }
      if (data.hasOwnProperty('jurisdiction_prefix')) {
        obj['jurisdiction_prefix'] = ApiClient.convertToType(data['jurisdiction_prefix'], 'String');
      }
      if (data.hasOwnProperty('origination')) {
        obj['origination'] = ApiClient.convertToType(data['origination'], 'Boolean');
      }
      if (data.hasOwnProperty('rates')) {
        obj['rates'] = ApiClient.convertToType(data['rates'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} resources
   */
  exports.prototype['resources'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} prefix_max_length
   */
  exports.prototype['prefix_max_length'] = undefined;
  /**
   * @member {Number} jur_type
   */
  exports.prototype['jur_type'] = undefined;
  /**
   * @member {Number} code_deck_id
   */
  exports.prototype['code_deck_id'] = undefined;
  /**
   * @member {Number} rate_type
   */
  exports.prototype['rate_type'] = undefined;
  /**
   * @member {Number} currency_id
   * @default 1
   */
  exports.prototype['currency_id'] = 1;
  /**
   * @member {Number} noprefix_min_length
   */
  exports.prototype['noprefix_min_length'] = undefined;
  /**
   * @member {module:model/RateTableEmpty.BillingMethodEnum} billing_method
   * @default 'DNIS'
   */
  exports.prototype['billing_method'] = 'DNIS';
  /**
   * @member {Number} lnp_dipping_rate
   */
  exports.prototype['lnp_dipping_rate'] = undefined;
  /**
   * @member {module:model/RateTableEmpty.RateTypeNameEnum} rate_type_name
   * @default 'A-Z'
   */
  exports.prototype['rate_type_name'] = 'A-Z';
  /**
   * @member {Number} noprefix_max_length
   */
  exports.prototype['noprefix_max_length'] = undefined;
  /**
   * @member {Number} jurisdiction_country_id
   */
  exports.prototype['jurisdiction_country_id'] = undefined;
  /**
   * @member {Boolean} is_virtual
   */
  exports.prototype['is_virtual'] = undefined;
  /**
   * @member {Number} prefix_min_length
   */
  exports.prototype['prefix_min_length'] = undefined;
  /**
   * @member {String} jurisdiction_prefix
   */
  exports.prototype['jurisdiction_prefix'] = undefined;
  /**
   * @member {Boolean} origination
   */
  exports.prototype['origination'] = undefined;
  /**
   * @member {Array.<String>} rates
   */
  exports.prototype['rates'] = undefined;


  /**
   * Allowed values for the <code>billing_method</code> property.
   * @enum {String}
   * @readonly
   */
  exports.BillingMethodEnum = {
    /**
     * value: "DNIS"
     * @const
     */
    "DNIS": "DNIS",
    /**
     * value: "LRN BLOCK"
     * @const
     */
    "LRN BLOCK": "LRN BLOCK",
    /**
     * value: "LRN"
     * @const
     */
    "LRN": "LRN"  };

  /**
   * Allowed values for the <code>rate_type_name</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RateTypeNameEnum = {
    /**
     * value: "OCN-LATA"
     * @const
     */
    "OCN-LATA": "OCN-LATA",
    /**
     * value: "US Non Jurisdictional"
     * @const
     */
    "US Non Jurisdictional": "US Non Jurisdictional",
    /**
     * value: "US Jurisdictional"
     * @const
     */
    "US Jurisdictional": "US Jurisdictional",
    /**
     * value: "A-Z"
     * @const
     */
    "A-Z": "A-Z"  };


  return exports;
}));


