/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DnlApi) {
      root.DnlApi = {};
    }
    root.DnlApi.RateMassEditLog = factory(root.DnlApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RateMassEditLog model module.
   * @module model/RateMassEditLog
   * @version 1.2.10
   */

  /**
   * Constructs a new <code>RateMassEditLog</code>.
   * @alias module:model/RateMassEditLog
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>RateMassEditLog</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RateMassEditLog} obj Optional instance to populate.
   * @return {module:model/RateMassEditLog} The populated <code>RateMassEditLog</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('client_id')) {
        obj['client_id'] = ApiClient.convertToType(data['client_id'], 'Number');
      }
      if (data.hasOwnProperty('action_time')) {
        obj['action_time'] = ApiClient.convertToType(data['action_time'], 'Date');
      }
      if (data.hasOwnProperty('down_file_path')) {
        obj['down_file_path'] = ApiClient.convertToType(data['down_file_path'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('rate_table_id')) {
        obj['rate_table_id'] = ApiClient.convertToType(data['rate_table_id'], 'Number');
      }
      if (data.hasOwnProperty('action_type')) {
        obj['action_type'] = ApiClient.convertToType(data['action_type'], 'String');
      }
      if (data.hasOwnProperty('action_rate_rows')) {
        obj['action_rate_rows'] = ApiClient.convertToType(data['action_rate_rows'], 'Number');
      }
      if (data.hasOwnProperty('client_name')) {
        obj['client_name'] = ApiClient.convertToType(data['client_name'], 'String');
      }
      if (data.hasOwnProperty('rate_table_name')) {
        obj['rate_table_name'] = ApiClient.convertToType(data['rate_table_name'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} client_id
   */
  exports.prototype['client_id'] = undefined;
  /**
   * @member {Date} action_time
   */
  exports.prototype['action_time'] = undefined;
  /**
   * @member {String} down_file_path
   */
  exports.prototype['down_file_path'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} rate_table_id
   */
  exports.prototype['rate_table_id'] = undefined;
  /**
   * @member {module:model/RateMassEditLog.ActionTypeEnum} action_type
   * @default 'delete found rates'
   */
  exports.prototype['action_type'] = 'delete found rates';
  /**
   * @member {Number} action_rate_rows
   */
  exports.prototype['action_rate_rows'] = undefined;
  /**
   * @member {String} client_name
   */
  exports.prototype['client_name'] = undefined;
  /**
   * @member {String} rate_table_name
   */
  exports.prototype['rate_table_name'] = undefined;


  /**
   * Allowed values for the <code>action_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ActionTypeEnum = {
    /**
     * value: "insert as new rates"
     * @const
     */
    "insert as new rates": "insert as new rates",
    /**
     * value: "update current rates"
     * @const
     */
    "update current rates": "update current rates",
    /**
     * value: "update all rates"
     * @const
     */
    "update all rates": "update all rates",
    /**
     * value: "delete found rates"
     * @const
     */
    "delete found rates": "delete found rates"  };


  return exports;
}));


