/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.62
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RateUploadTaskInfoFieldNames', 'model/RateUploadTaskInfoTimeIntervals'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RateUploadTaskInfoFieldNames'), require('./RateUploadTaskInfoTimeIntervals'));
  } else {
    // Browser globals (root is window)
    if (!root.DnlApi) {
      root.DnlApi = {};
    }
    root.DnlApi.RateUploadTaskInfo = factory(root.DnlApi.ApiClient, root.DnlApi.RateUploadTaskInfoFieldNames, root.DnlApi.RateUploadTaskInfoTimeIntervals);
  }
}(this, function(ApiClient, RateUploadTaskInfoFieldNames, RateUploadTaskInfoTimeIntervals) {
  'use strict';




  /**
   * The RateUploadTaskInfo model module.
   * @module model/RateUploadTaskInfo
   * @version 1.2.62
   */

  /**
   * Constructs a new <code>RateUploadTaskInfo</code>.
   * @alias module:model/RateUploadTaskInfo
   * @class
   * @param fields {module:model/RateUploadTaskInfoFieldNames} 
   */
  var exports = function(fields) {
    var _this = this;


    _this['fields'] = fields;

  };

  /**
   * Constructs a <code>RateUploadTaskInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RateUploadTaskInfo} obj Optional instance to populate.
   * @return {module:model/RateUploadTaskInfo} The populated <code>RateUploadTaskInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('time_intervals')) {
        obj['time_intervals'] = ApiClient.convertToType(data['time_intervals'], [RateUploadTaskInfoTimeIntervals]);
      }
      if (data.hasOwnProperty('fields')) {
        obj['fields'] = RateUploadTaskInfoFieldNames.constructFromObject(data['fields']);
      }
      if (data.hasOwnProperty('effective_date_default')) {
        obj['effective_date_default'] = ApiClient.convertToType(data['effective_date_default'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RateUploadTaskInfoTimeIntervals>} time_intervals
   */
  exports.prototype['time_intervals'] = undefined;
  /**
   * @member {module:model/RateUploadTaskInfoFieldNames} fields
   */
  exports.prototype['fields'] = undefined;
  /**
   * @member {String} effective_date_default
   */
  exports.prototype['effective_date_default'] = undefined;



  return exports;
}));


