/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.62
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DnlApi) {
      root.DnlApi = {};
    }
    root.DnlApi.ResourceBlock = factory(root.DnlApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ResourceBlock model module.
   * @module model/ResourceBlock
   * @version 1.2.62
   */

  /**
   * Constructs a new <code>ResourceBlock</code>.
   * @alias module:model/ResourceBlock
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>ResourceBlock</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResourceBlock} obj Optional instance to populate.
   * @return {module:model/ResourceBlock} The populated <code>ResourceBlock</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ingress_trunk_id')) {
        obj['ingress_trunk_id'] = ApiClient.convertToType(data['ingress_trunk_id'], 'Number');
      }
      if (data.hasOwnProperty('DNIS_min')) {
        obj['DNIS_min'] = ApiClient.convertToType(data['DNIS_min'], 'Number');
      }
      if (data.hasOwnProperty('DNIS_prefix')) {
        obj['DNIS_prefix'] = ApiClient.convertToType(data['DNIS_prefix'], 'String');
      }
      if (data.hasOwnProperty('DNIS_max')) {
        obj['DNIS_max'] = ApiClient.convertToType(data['DNIS_max'], 'Number');
      }
      if (data.hasOwnProperty('ANI_empty')) {
        obj['ANI_empty'] = ApiClient.convertToType(data['ANI_empty'], 'Boolean');
      }
      if (data.hasOwnProperty('ANI_min')) {
        obj['ANI_min'] = ApiClient.convertToType(data['ANI_min'], 'Number');
      }
      if (data.hasOwnProperty('egress_trunk_id')) {
        obj['egress_trunk_id'] = ApiClient.convertToType(data['egress_trunk_id'], 'Number');
      }
      if (data.hasOwnProperty('egress_group_id')) {
        obj['egress_group_id'] = ApiClient.convertToType(data['egress_group_id'], 'Number');
      }
      if (data.hasOwnProperty('time_profile_id')) {
        obj['time_profile_id'] = ApiClient.convertToType(data['time_profile_id'], 'Number');
      }
      if (data.hasOwnProperty('block_type')) {
        obj['block_type'] = ApiClient.convertToType(data['block_type'], 'String');
      }
      if (data.hasOwnProperty('ANI_prefix')) {
        obj['ANI_prefix'] = ApiClient.convertToType(data['ANI_prefix'], 'String');
      }
      if (data.hasOwnProperty('ANI_max')) {
        obj['ANI_max'] = ApiClient.convertToType(data['ANI_max'], 'Number');
      }
      if (data.hasOwnProperty('ingress_group_id')) {
        obj['ingress_group_id'] = ApiClient.convertToType(data['ingress_group_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} ingress_trunk_id
   */
  exports.prototype['ingress_trunk_id'] = undefined;
  /**
   * @member {Number} DNIS_min
   */
  exports.prototype['DNIS_min'] = undefined;
  /**
   * @member {String} DNIS_prefix
   */
  exports.prototype['DNIS_prefix'] = undefined;
  /**
   * @member {Number} DNIS_max
   */
  exports.prototype['DNIS_max'] = undefined;
  /**
   * @member {Boolean} ANI_empty
   */
  exports.prototype['ANI_empty'] = undefined;
  /**
   * @member {Number} ANI_min
   */
  exports.prototype['ANI_min'] = undefined;
  /**
   * @member {Number} egress_trunk_id
   */
  exports.prototype['egress_trunk_id'] = undefined;
  /**
   * @member {Number} egress_group_id
   */
  exports.prototype['egress_group_id'] = undefined;
  /**
   * @member {Number} time_profile_id
   */
  exports.prototype['time_profile_id'] = undefined;
  /**
   * @member {module:model/ResourceBlock.BlockTypeEnum} block_type
   */
  exports.prototype['block_type'] = undefined;
  /**
   * @member {String} ANI_prefix
   */
  exports.prototype['ANI_prefix'] = undefined;
  /**
   * @member {Number} ANI_max
   */
  exports.prototype['ANI_max'] = undefined;
  /**
   * @member {Number} ingress_group_id
   */
  exports.prototype['ingress_group_id'] = undefined;


  /**
   * Allowed values for the <code>block_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.BlockTypeEnum = {
    /**
     * value: "specific group"
     * @const
     */
    "group": "specific group",
    /**
     * value: "specific trunk"
     * @const
     */
    "trunk": "specific trunk",
    /**
     * value: "specific carrier"
     * @const
     */
    "carrier": "specific carrier"  };


  return exports;
}));


