/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.62
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DnlApi) {
      root.DnlApi = {};
    }
    root.DnlApi.TrunkGroup = factory(root.DnlApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TrunkGroup model module.
   * @module model/TrunkGroup
   * @version 1.2.62
   */

  /**
   * Constructs a new <code>TrunkGroup</code>.
   * @alias module:model/TrunkGroup
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>TrunkGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrunkGroup} obj Optional instance to populate.
   * @return {module:model/TrunkGroup} The populated <code>TrunkGroup</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('all_trunks')) {
        obj['all_trunks'] = ApiClient.convertToType(data['all_trunks'], ['Number']);
      }
      if (data.hasOwnProperty('trunk_type')) {
        obj['trunk_type'] = ApiClient.convertToType(data['trunk_type'], 'String');
      }
      if (data.hasOwnProperty('group_name')) {
        obj['group_name'] = ApiClient.convertToType(data['group_name'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<Number>} all_trunks
   */
  exports.prototype['all_trunks'] = undefined;
  /**
   * @member {module:model/TrunkGroup.TrunkTypeEnum} trunk_type
   * @default 'ingress'
   */
  exports.prototype['trunk_type'] = 'ingress';
  /**
   * @member {String} group_name
   */
  exports.prototype['group_name'] = undefined;


  /**
   * Allowed values for the <code>trunk_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TrunkTypeEnum = {
    /**
     * value: "ingress"
     * @const
     */
    "ingress": "ingress",
    /**
     * value: "egress"
     * @const
     */
    "egress": "egress"  };


  return exports;
}));


