/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.62
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/VendorResourceDidGet'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./VendorResourceDidGet'));
  } else {
    // Browser globals (root is window)
    if (!root.DnlApi) {
      root.DnlApi = {};
    }
    root.DnlApi.VendorDidGet = factory(root.DnlApi.ApiClient, root.DnlApi.VendorResourceDidGet);
  }
}(this, function(ApiClient, VendorResourceDidGet) {
  'use strict';




  /**
   * The VendorDidGet model module.
   * @module model/VendorDidGet
   * @version 1.2.62
   */

  /**
   * Constructs a new <code>VendorDidGet</code>.
   * @alias module:model/VendorDidGet
   * @class
   * @param name {String} 
   */
  var exports = function(name) {
    var _this = this;










    _this['name'] = name;
  };

  /**
   * Constructs a <code>VendorDidGet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VendorDidGet} obj Optional instance to populate.
   * @return {module:model/VendorDidGet} The populated <code>VendorDidGet</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('client_id')) {
        obj['client_id'] = ApiClient.convertToType(data['client_id'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
      }
      if (data.hasOwnProperty('update_by')) {
        obj['update_by'] = ApiClient.convertToType(data['update_by'], 'String');
      }
      if (data.hasOwnProperty('vendor_billing_rule_id')) {
        obj['vendor_billing_rule_id'] = ApiClient.convertToType(data['vendor_billing_rule_id'], 'Number');
      }
      if (data.hasOwnProperty('resource')) {
        obj['resource'] = VendorResourceDidGet.constructFromObject(data['resource']);
      }
      if (data.hasOwnProperty('balance')) {
        obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
      }
      if (data.hasOwnProperty('billing_method')) {
        obj['billing_method'] = ApiClient.convertToType(data['billing_method'], 'String');
      }
      if (data.hasOwnProperty('update_at')) {
        obj['update_at'] = ApiClient.convertToType(data['update_at'], 'Date');
      }
      if (data.hasOwnProperty('call_limit')) {
        obj['call_limit'] = ApiClient.convertToType(data['call_limit'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} client_id
   */
  exports.prototype['client_id'] = undefined;
  /**
   * @member {Boolean} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} update_by
   */
  exports.prototype['update_by'] = undefined;
  /**
   * @member {Number} vendor_billing_rule_id
   */
  exports.prototype['vendor_billing_rule_id'] = undefined;
  /**
   * @member {module:model/VendorResourceDidGet} resource
   */
  exports.prototype['resource'] = undefined;
  /**
   * @member {Number} balance
   */
  exports.prototype['balance'] = undefined;
  /**
   * @member {module:model/VendorDidGet.BillingMethodEnum} billing_method
   * @default 'percentage'
   */
  exports.prototype['billing_method'] = 'percentage';
  /**
   * @member {Date} update_at
   */
  exports.prototype['update_at'] = undefined;
  /**
   * @member {Number} call_limit
   */
  exports.prototype['call_limit'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;


  /**
   * Allowed values for the <code>billing_method</code> property.
   * @enum {String}
   * @readonly
   */
  exports.BillingMethodEnum = {
    /**
     * value: "percentage"
     * @const
     */
    "percentage": "percentage",
    /**
     * value: "value"
     * @const
     */
    "value": "value"  };


  return exports;
}));


