/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AttributeNotExists', 'model/Carrier', 'model/CarrierAllertSettings', 'model/CarrierContacts', 'model/CarrierGroup', 'model/CarrierInvoiceSetting', 'model/CarrierLong', 'model/CarrierLowBalanceConfig', 'model/CarrierPassword', 'model/CarrierPortal', 'model/CarrierScc', 'model/CarrierTemplateFromClient', 'model/ClientCredit', 'model/EgressTrunk', 'model/IngressTrunk', 'model/IngressTrunkModify', 'model/InlineResponse20012', 'model/InlineResponse20013', 'model/InlineResponse20014', 'model/InlineResponse20015', 'model/InlineResponse20016', 'model/InlineResponse20017', 'model/InlineResponse20018', 'model/InlineResponse20019', 'model/InlineResponse20020', 'model/InlineResponse20021', 'model/InlineResponse20022', 'model/InlineResponse20023', 'model/InlineResponse20024', 'model/InlineResponse20025', 'model/InlineResponse20026', 'model/InlineResponse20027', 'model/InlineResponse20028', 'model/InlineResponse20029', 'model/ObjectCreated', 'model/ObjectNotFoundError', 'model/OperationError', 'model/Success', 'model/UnauthenticatedError', 'model/ValidationError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AttributeNotExists'), require('../model/Carrier'), require('../model/CarrierAllertSettings'), require('../model/CarrierContacts'), require('../model/CarrierGroup'), require('../model/CarrierInvoiceSetting'), require('../model/CarrierLong'), require('../model/CarrierLowBalanceConfig'), require('../model/CarrierPassword'), require('../model/CarrierPortal'), require('../model/CarrierScc'), require('../model/CarrierTemplateFromClient'), require('../model/ClientCredit'), require('../model/EgressTrunk'), require('../model/IngressTrunk'), require('../model/IngressTrunkModify'), require('../model/InlineResponse20012'), require('../model/InlineResponse20013'), require('../model/InlineResponse20014'), require('../model/InlineResponse20015'), require('../model/InlineResponse20016'), require('../model/InlineResponse20017'), require('../model/InlineResponse20018'), require('../model/InlineResponse20019'), require('../model/InlineResponse20020'), require('../model/InlineResponse20021'), require('../model/InlineResponse20022'), require('../model/InlineResponse20023'), require('../model/InlineResponse20024'), require('../model/InlineResponse20025'), require('../model/InlineResponse20026'), require('../model/InlineResponse20027'), require('../model/InlineResponse20028'), require('../model/InlineResponse20029'), require('../model/ObjectCreated'), require('../model/ObjectNotFoundError'), require('../model/OperationError'), require('../model/Success'), require('../model/UnauthenticatedError'), require('../model/ValidationError'));
  } else {
    // Browser globals (root is window)
    if (!root.DnlApi) {
      root.DnlApi = {};
    }
    root.DnlApi.CarrierApi = factory(root.DnlApi.ApiClient, root.DnlApi.AttributeNotExists, root.DnlApi.Carrier, root.DnlApi.CarrierAllertSettings, root.DnlApi.CarrierContacts, root.DnlApi.CarrierGroup, root.DnlApi.CarrierInvoiceSetting, root.DnlApi.CarrierLong, root.DnlApi.CarrierLowBalanceConfig, root.DnlApi.CarrierPassword, root.DnlApi.CarrierPortal, root.DnlApi.CarrierScc, root.DnlApi.CarrierTemplateFromClient, root.DnlApi.ClientCredit, root.DnlApi.EgressTrunk, root.DnlApi.IngressTrunk, root.DnlApi.IngressTrunkModify, root.DnlApi.InlineResponse20012, root.DnlApi.InlineResponse20013, root.DnlApi.InlineResponse20014, root.DnlApi.InlineResponse20015, root.DnlApi.InlineResponse20016, root.DnlApi.InlineResponse20017, root.DnlApi.InlineResponse20018, root.DnlApi.InlineResponse20019, root.DnlApi.InlineResponse20020, root.DnlApi.InlineResponse20021, root.DnlApi.InlineResponse20022, root.DnlApi.InlineResponse20023, root.DnlApi.InlineResponse20024, root.DnlApi.InlineResponse20025, root.DnlApi.InlineResponse20026, root.DnlApi.InlineResponse20027, root.DnlApi.InlineResponse20028, root.DnlApi.InlineResponse20029, root.DnlApi.ObjectCreated, root.DnlApi.ObjectNotFoundError, root.DnlApi.OperationError, root.DnlApi.Success, root.DnlApi.UnauthenticatedError, root.DnlApi.ValidationError);
  }
}(this, function(ApiClient, AttributeNotExists, Carrier, CarrierAllertSettings, CarrierContacts, CarrierGroup, CarrierInvoiceSetting, CarrierLong, CarrierLowBalanceConfig, CarrierPassword, CarrierPortal, CarrierScc, CarrierTemplateFromClient, ClientCredit, EgressTrunk, IngressTrunk, IngressTrunkModify, InlineResponse20012, InlineResponse20013, InlineResponse20014, InlineResponse20015, InlineResponse20016, InlineResponse20017, InlineResponse20018, InlineResponse20019, InlineResponse20020, InlineResponse20021, InlineResponse20022, InlineResponse20023, InlineResponse20024, InlineResponse20025, InlineResponse20026, InlineResponse20027, InlineResponse20028, InlineResponse20029, ObjectCreated, ObjectNotFoundError, OperationError, Success, UnauthenticatedError, ValidationError) {
  'use strict';

  /**
   * Carrier service.
   * @module api/CarrierApi
   * @version 1.2.10
   */

  /**
   * Constructs a new CarrierApi. 
   * @alias module:api/CarrierApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the carrierBasicCreatePost operation.
     * @callback module:api/CarrierApi~carrierBasicCreatePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ObjectCreated} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates new carrier
     * @param {Object} opts Optional parameters
     * @param {module:model/Carrier} opts.body Carrier to create
     * @param {module:api/CarrierApi~carrierBasicCreatePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ObjectCreated}
     */
    this.carrierBasicCreatePost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ObjectCreated;

      return this.apiClient.callApi(
        '/carrier/basic/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdAlertsGet operation.
     * @callback module:api/CarrierApi~carrierClientIdAlertsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20016} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {module:api/CarrierApi~carrierClientIdAlertsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20016}
     */
    this.carrierClientIdAlertsGet = function(clientId, callback) {
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdAlertsGet");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20016;

      return this.apiClient.callApi(
        '/carrier/{client_id}/alerts', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdAlertsPatch operation.
     * @callback module:api/CarrierApi~carrierClientIdAlertsPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20016} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierAllertSettings} opts.body Carrier to modify
     * @param {module:api/CarrierApi~carrierClientIdAlertsPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20016}
     */
    this.carrierClientIdAlertsPatch = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdAlertsPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20016;

      return this.apiClient.callApi(
        '/carrier/{client_id}/alerts', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdContactsGet operation.
     * @callback module:api/CarrierApi~carrierClientIdContactsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20020} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {module:api/CarrierApi~carrierClientIdContactsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20020}
     */
    this.carrierClientIdContactsGet = function(clientId, callback) {
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdContactsGet");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20020;

      return this.apiClient.callApi(
        '/carrier/{client_id}/contacts', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdContactsPatch operation.
     * @callback module:api/CarrierApi~carrierClientIdContactsPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20020} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierContacts} opts.body Carrier to modify
     * @param {module:api/CarrierApi~carrierClientIdContactsPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20020}
     */
    this.carrierClientIdContactsPatch = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdContactsPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20020;

      return this.apiClient.callApi(
        '/carrier/{client_id}/contacts', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdDelete operation.
     * @callback module:api/CarrierApi~carrierClientIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Success} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {module:api/CarrierApi~carrierClientIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Success}
     */
    this.carrierClientIdDelete = function(clientId, callback) {
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdDelete");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Success;

      return this.apiClient.callApi(
        '/carrier/{client_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdEgressTrunkListGet operation.
     * @callback module:api/CarrierApi~carrierClientIdEgressTrunkListGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20023} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets egresstrunks
     * @param {Number} clientId Parent carrier
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page 
     * @param {Number} opts.perPage 
     * @param {module:model/String} opts.orderBy 
     * @param {module:model/String} opts.orderDir 
     * @param {String} opts.carrierId 
     * @param {Boolean} opts.isActive 
     * @param {String} opts.name 
     * @param {Number} opts.resourceId 
     * @param {Number} opts.resourceTemplateId 
     * @param {Number} opts.trunkId 
     * @param {String} opts.trunkName 
     * @param {module:api/CarrierApi~carrierClientIdEgressTrunkListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20023}
     */
    this.carrierClientIdEgressTrunkListGet = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdEgressTrunkListGet");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
        'page': opts['page'],
        'per_page': opts['perPage'],
        'order_by': opts['orderBy'],
        'order_dir': opts['orderDir'],
        'carrier_id': opts['carrierId'],
        'is_active': opts['isActive'],
        'name': opts['name'],
        'resource_id': opts['resourceId'],
        'resource_template_id': opts['resourceTemplateId'],
        'trunk_id': opts['trunkId'],
        'trunk_name': opts['trunkName']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20023;

      return this.apiClient.callApi(
        '/carrier/{client_id}/egress_trunk/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdEgressTrunkPost operation.
     * @callback module:api/CarrierApi~carrierClientIdEgressTrunkPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ObjectCreated} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates new egresstrunk
     * @param {Number} clientId Parent carrier
     * @param {Object} opts Optional parameters
     * @param {module:model/EgressTrunk} opts.body EgressTrunk to create
     * @param {module:api/CarrierApi~carrierClientIdEgressTrunkPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ObjectCreated}
     */
    this.carrierClientIdEgressTrunkPost = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdEgressTrunkPost");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ObjectCreated;

      return this.apiClient.callApi(
        '/carrier/{client_id}/egress_trunk', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdGet operation.
     * @callback module:api/CarrierApi~carrierClientIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20014} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {module:api/CarrierApi~carrierClientIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20014}
     */
    this.carrierClientIdGet = function(clientId, callback) {
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdGet");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20014;

      return this.apiClient.callApi(
        '/carrier/{client_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdIngressTrunkListGet operation.
     * @callback module:api/CarrierApi~carrierClientIdIngressTrunkListGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20025} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets ingresstrunks
     * @param {Number} clientId Parent carrier
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page 
     * @param {Number} opts.perPage 
     * @param {module:model/String} opts.orderBy 
     * @param {module:model/String} opts.orderDir 
     * @param {Number} opts.callLimit 
     * @param {String} opts.carrierId 
     * @param {Number} opts.cpsLimit 
     * @param {Boolean} opts.isActive 
     * @param {String} opts.name 
     * @param {Number} opts.resourceId 
     * @param {Number} opts.resourceTemplateId 
     * @param {Number} opts.trunkId 
     * @param {String} opts.trunkName 
     * @param {String} opts.updateBy 
     * @param {String} opts.updateAtGt 
     * @param {String} opts.updateAtLt 
     * @param {module:api/CarrierApi~carrierClientIdIngressTrunkListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20025}
     */
    this.carrierClientIdIngressTrunkListGet = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdIngressTrunkListGet");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
        'page': opts['page'],
        'per_page': opts['perPage'],
        'order_by': opts['orderBy'],
        'order_dir': opts['orderDir'],
        'call_limit': opts['callLimit'],
        'carrier_id': opts['carrierId'],
        'cps_limit': opts['cpsLimit'],
        'is_active': opts['isActive'],
        'name': opts['name'],
        'resource_id': opts['resourceId'],
        'resource_template_id': opts['resourceTemplateId'],
        'trunk_id': opts['trunkId'],
        'trunk_name': opts['trunkName'],
        'update_by': opts['updateBy'],
        'update_at_gt': opts['updateAtGt'],
        'update_at_lt': opts['updateAtLt']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20025;

      return this.apiClient.callApi(
        '/carrier/{client_id}/ingress_trunk/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdIngressTrunkPost operation.
     * @callback module:api/CarrierApi~carrierClientIdIngressTrunkPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ObjectCreated} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates new ingresstrunk
     * @param {Number} clientId Parent carrier
     * @param {Object} opts Optional parameters
     * @param {module:model/IngressTrunk} opts.body IngressTrunk to create
     * @param {module:api/CarrierApi~carrierClientIdIngressTrunkPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ObjectCreated}
     */
    this.carrierClientIdIngressTrunkPost = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdIngressTrunkPost");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ObjectCreated;

      return this.apiClient.callApi(
        '/carrier/{client_id}/ingress_trunk', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdInvoicesGet operation.
     * @callback module:api/CarrierApi~carrierClientIdInvoicesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20017} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {module:api/CarrierApi~carrierClientIdInvoicesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20017}
     */
    this.carrierClientIdInvoicesGet = function(clientId, callback) {
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdInvoicesGet");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20017;

      return this.apiClient.callApi(
        '/carrier/{client_id}/invoices', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdInvoicesPatch operation.
     * @callback module:api/CarrierApi~carrierClientIdInvoicesPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20017} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierInvoiceSetting} opts.body Carrier to modify
     * @param {module:api/CarrierApi~carrierClientIdInvoicesPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20017}
     */
    this.carrierClientIdInvoicesPatch = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdInvoicesPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20017;

      return this.apiClient.callApi(
        '/carrier/{client_id}/invoices', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdLowBalanceConfigGet operation.
     * @callback module:api/CarrierApi~carrierClientIdLowBalanceConfigGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20021} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets carrierlowbalanceconfig
     * @param {Number} clientId CarrierLowBalanceConfig id to get info about
     * @param {module:api/CarrierApi~carrierClientIdLowBalanceConfigGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20021}
     */
    this.carrierClientIdLowBalanceConfigGet = function(clientId, callback) {
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdLowBalanceConfigGet");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20021;

      return this.apiClient.callApi(
        '/carrier/{client_id}/low_balance_config', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdLowBalanceConfigPatch operation.
     * @callback module:api/CarrierApi~carrierClientIdLowBalanceConfigPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20021} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies carrierlowbalanceconfig
     * @param {Number} clientId CarrierLowBalanceConfig id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierLowBalanceConfig} opts.body CarrierLowBalanceConfig to modify
     * @param {module:api/CarrierApi~carrierClientIdLowBalanceConfigPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20021}
     */
    this.carrierClientIdLowBalanceConfigPatch = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdLowBalanceConfigPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20021;

      return this.apiClient.callApi(
        '/carrier/{client_id}/low_balance_config', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdPasswordPatch operation.
     * @callback module:api/CarrierApi~carrierClientIdPasswordPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20028} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierPassword} opts.body Carrier to modify
     * @param {module:api/CarrierApi~carrierClientIdPasswordPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20028}
     */
    this.carrierClientIdPasswordPatch = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdPasswordPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20028;

      return this.apiClient.callApi(
        '/carrier/{client_id}/password', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdPatch operation.
     * @callback module:api/CarrierApi~carrierClientIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20014} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/Carrier} opts.body Carrier to modify
     * @param {module:api/CarrierApi~carrierClientIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20014}
     */
    this.carrierClientIdPatch = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20014;

      return this.apiClient.callApi(
        '/carrier/{client_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdPortalGet operation.
     * @callback module:api/CarrierApi~carrierClientIdPortalGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20019} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {module:api/CarrierApi~carrierClientIdPortalGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20019}
     */
    this.carrierClientIdPortalGet = function(clientId, callback) {
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdPortalGet");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20019;

      return this.apiClient.callApi(
        '/carrier/{client_id}/portal', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdPortalPatch operation.
     * @callback module:api/CarrierApi~carrierClientIdPortalPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20019} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierPortal} opts.body Carrier to modify
     * @param {module:api/CarrierApi~carrierClientIdPortalPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20019}
     */
    this.carrierClientIdPortalPatch = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdPortalPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20019;

      return this.apiClient.callApi(
        '/carrier/{client_id}/portal', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdSaveAsTemplatePost operation.
     * @callback module:api/CarrierApi~carrierClientIdSaveAsTemplatePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ObjectCreated} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates new carriertemplate
     * @param {Number} clientId Parent carrier
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierTemplateFromClient} opts.body CarrierTemplate to create
     * @param {module:api/CarrierApi~carrierClientIdSaveAsTemplatePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ObjectCreated}
     */
    this.carrierClientIdSaveAsTemplatePost = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdSaveAsTemplatePost");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ObjectCreated;

      return this.apiClient.callApi(
        '/carrier/{client_id}/save_as_template', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdSccGet operation.
     * @callback module:api/CarrierApi~carrierClientIdSccGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20018} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {module:api/CarrierApi~carrierClientIdSccGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20018}
     */
    this.carrierClientIdSccGet = function(clientId, callback) {
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdSccGet");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20018;

      return this.apiClient.callApi(
        '/carrier/{client_id}/scc', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdSccPatch operation.
     * @callback module:api/CarrierApi~carrierClientIdSccPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20018} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies carrier
     * @param {Number} clientId Carrier id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierScc} opts.body Carrier to modify
     * @param {module:api/CarrierApi~carrierClientIdSccPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20018}
     */
    this.carrierClientIdSccPatch = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdSccPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20018;

      return this.apiClient.callApi(
        '/carrier/{client_id}/scc', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdSendLowBalanceAlertPatch operation.
     * @callback module:api/CarrierApi~carrierClientIdSendLowBalanceAlertPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Success} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * @param {Number} clientId Carrier to proceed
     * @param {module:api/CarrierApi~carrierClientIdSendLowBalanceAlertPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Success}
     */
    this.carrierClientIdSendLowBalanceAlertPatch = function(clientId, callback) {
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdSendLowBalanceAlertPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Success;

      return this.apiClient.callApi(
        '/carrier/{client_id}/send_low_balance_alert', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierClientIdSendWelcomPatch operation.
     * @callback module:api/CarrierApi~carrierClientIdSendWelcomPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Success} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * @param {Number} clientId Carrier to proceed
     * @param {module:api/CarrierApi~carrierClientIdSendWelcomPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Success}
     */
    this.carrierClientIdSendWelcomPatch = function(clientId, callback) {
      var postBody = null;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling carrierClientIdSendWelcomPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Success;

      return this.apiClient.callApi(
        '/carrier/{client_id}/send_welcom', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierFullCreatePost operation.
     * @callback module:api/CarrierApi~carrierFullCreatePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ObjectCreated} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates new carrier
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierLong} opts.body Carrier to create
     * @param {module:api/CarrierApi~carrierFullCreatePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ObjectCreated}
     */
    this.carrierFullCreatePost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ObjectCreated;

      return this.apiClient.callApi(
        '/carrier/full/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierGroupCreatePost operation.
     * @callback module:api/CarrierApi~carrierGroupCreatePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ObjectCreated} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates new carriergroup
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierGroup} opts.body CarrierGroup to create
     * @param {module:api/CarrierApi~carrierGroupCreatePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ObjectCreated}
     */
    this.carrierGroupCreatePost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ObjectCreated;

      return this.apiClient.callApi(
        '/carrier/group/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierGroupGroupIdDelete operation.
     * @callback module:api/CarrierApi~carrierGroupGroupIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Success} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes carriergroup
     * @param {Number} groupId CarrierGroup id to get info about
     * @param {module:api/CarrierApi~carrierGroupGroupIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Success}
     */
    this.carrierGroupGroupIdDelete = function(groupId, callback) {
      var postBody = null;

      // verify the required parameter 'groupId' is set
      if (groupId === undefined || groupId === null) {
        throw new Error("Missing the required parameter 'groupId' when calling carrierGroupGroupIdDelete");
      }


      var pathParams = {
        'group_id': groupId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Success;

      return this.apiClient.callApi(
        '/carrier/group/{group_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierGroupGroupIdGet operation.
     * @callback module:api/CarrierApi~carrierGroupGroupIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20012} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets carriergroup
     * @param {Number} groupId CarrierGroup id to get info about
     * @param {module:api/CarrierApi~carrierGroupGroupIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20012}
     */
    this.carrierGroupGroupIdGet = function(groupId, callback) {
      var postBody = null;

      // verify the required parameter 'groupId' is set
      if (groupId === undefined || groupId === null) {
        throw new Error("Missing the required parameter 'groupId' when calling carrierGroupGroupIdGet");
      }


      var pathParams = {
        'group_id': groupId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20012;

      return this.apiClient.callApi(
        '/carrier/group/{group_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierGroupGroupIdPatch operation.
     * @callback module:api/CarrierApi~carrierGroupGroupIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20012} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies carriergroup
     * @param {Number} groupId CarrierGroup id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/CarrierGroup} opts.body CarrierGroup to modify
     * @param {module:api/CarrierApi~carrierGroupGroupIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20012}
     */
    this.carrierGroupGroupIdPatch = function(groupId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'groupId' is set
      if (groupId === undefined || groupId === null) {
        throw new Error("Missing the required parameter 'groupId' when calling carrierGroupGroupIdPatch");
      }


      var pathParams = {
        'group_id': groupId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20012;

      return this.apiClient.callApi(
        '/carrier/group/{group_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierGroupListGet operation.
     * @callback module:api/CarrierApi~carrierGroupListGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20013} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets carriergroups
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page 
     * @param {Number} opts.perPage 
     * @param {module:model/String} opts.orderBy 
     * @param {module:model/String} opts.orderDir 
     * @param {Number} opts.groupId 
     * @param {String} opts.groupName 
     * @param {module:api/CarrierApi~carrierGroupListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20013}
     */
    this.carrierGroupListGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'page': opts['page'],
        'per_page': opts['perPage'],
        'order_by': opts['orderBy'],
        'order_dir': opts['orderDir'],
        'group_id': opts['groupId'],
        'group_name': opts['groupName']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20013;

      return this.apiClient.callApi(
        '/carrier/group/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the carrierListGet operation.
     * @callback module:api/CarrierApi~carrierListGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20015} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets carriers
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page 
     * @param {Number} opts.perPage 
     * @param {module:model/String} opts.orderBy 
     * @param {module:model/String} opts.orderDir 
     * @param {Number} opts.carrierTemplateId 
     * @param {String} opts.company 
     * @param {Number} opts.egressCount 
     * @param {Number} opts.ingressCount 
     * @param {Number} opts.ingressCountSql 
     * @param {Boolean} opts.isActive 
     * @param {Boolean} opts.isPrepay 
     * @param {String} opts.name 
     * @param {String} opts.updateBy 
     * @param {String} opts.creditLimitGt 
     * @param {String} opts.creditLimitLt 
     * @param {String} opts.updateAtGt 
     * @param {String} opts.updateAtLt 
     * @param {module:api/CarrierApi~carrierListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20015}
     */
    this.carrierListGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'page': opts['page'],
        'per_page': opts['perPage'],
        'order_by': opts['orderBy'],
        'order_dir': opts['orderDir'],
        'carrier_template_id': opts['carrierTemplateId'],
        'company': opts['company'],
        'egress_count': opts['egressCount'],
        'ingress_count': opts['ingressCount'],
        'ingress_count_sql': opts['ingressCountSql'],
        'is_active': opts['isActive'],
        'is_prepay': opts['isPrepay'],
        'name': opts['name'],
        'update_by': opts['updateBy'],
        'credit_limit_gt': opts['creditLimitGt'],
        'credit_limit_lt': opts['creditLimitLt'],
        'update_at_gt': opts['updateAtGt'],
        'update_at_lt': opts['updateAtLt']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20015;

      return this.apiClient.callApi(
        '/carrier/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the clientCreditClientIdPatch operation.
     * @callback module:api/CarrierApi~clientCreditClientIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20026} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies clientcredit
     * @param {Number} clientId ClientCredit id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/ClientCredit} opts.body ClientCredit to modify
     * @param {module:api/CarrierApi~clientCreditClientIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20026}
     */
    this.clientCreditClientIdPatch = function(clientId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling clientCreditClientIdPatch");
      }


      var pathParams = {
        'client_id': clientId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20026;

      return this.apiClient.callApi(
        '/client/credit/{client_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the clientCreditListGet operation.
     * @callback module:api/CarrierApi~clientCreditListGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20027} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets clientcredits
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page 
     * @param {Number} opts.perPage 
     * @param {module:model/String} opts.orderBy 
     * @param {module:model/String} opts.orderDir 
     * @param {Boolean} opts.active 
     * @param {module:api/CarrierApi~clientCreditListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20027}
     */
    this.clientCreditListGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'page': opts['page'],
        'per_page': opts['perPage'],
        'order_by': opts['orderBy'],
        'order_dir': opts['orderDir'],
        'active': opts['active']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20027;

      return this.apiClient.callApi(
        '/client/credit/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the clientPastDueListGet operation.
     * @callback module:api/CarrierApi~clientPastDueListGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20029} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets past due report
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page 
     * @param {Number} opts.perPage 
     * @param {module:model/String} opts.orderBy 
     * @param {module:model/String} opts.orderDir 
     * @param {Number} opts.clientId 
     * @param {String} opts.name 
     * @param {module:api/CarrierApi~clientPastDueListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20029}
     */
    this.clientPastDueListGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'page': opts['page'],
        'per_page': opts['perPage'],
        'order_by': opts['orderBy'],
        'order_dir': opts['orderDir'],
        'client_id': opts['clientId'],
        'name': opts['name']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20029;

      return this.apiClient.callApi(
        '/client/past_due/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the egressTrunkResourceIdDelete operation.
     * @callback module:api/CarrierApi~egressTrunkResourceIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Success} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes egresstrunk
     * @param {Number} resourceId EgressTrunk id to get info about
     * @param {module:api/CarrierApi~egressTrunkResourceIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Success}
     */
    this.egressTrunkResourceIdDelete = function(resourceId, callback) {
      var postBody = null;

      // verify the required parameter 'resourceId' is set
      if (resourceId === undefined || resourceId === null) {
        throw new Error("Missing the required parameter 'resourceId' when calling egressTrunkResourceIdDelete");
      }


      var pathParams = {
        'resource_id': resourceId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Success;

      return this.apiClient.callApi(
        '/egress_trunk/{resource_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the egressTrunkResourceIdGet operation.
     * @callback module:api/CarrierApi~egressTrunkResourceIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20022} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets egresstrunk
     * @param {Number} resourceId EgressTrunk id to get info about
     * @param {module:api/CarrierApi~egressTrunkResourceIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20022}
     */
    this.egressTrunkResourceIdGet = function(resourceId, callback) {
      var postBody = null;

      // verify the required parameter 'resourceId' is set
      if (resourceId === undefined || resourceId === null) {
        throw new Error("Missing the required parameter 'resourceId' when calling egressTrunkResourceIdGet");
      }


      var pathParams = {
        'resource_id': resourceId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20022;

      return this.apiClient.callApi(
        '/egress_trunk/{resource_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the egressTrunkResourceIdPatch operation.
     * @callback module:api/CarrierApi~egressTrunkResourceIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20022} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies egresstrunk
     * @param {Number} resourceId EgressTrunk id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/EgressTrunk} opts.body EgressTrunk to modify
     * @param {module:api/CarrierApi~egressTrunkResourceIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20022}
     */
    this.egressTrunkResourceIdPatch = function(resourceId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'resourceId' is set
      if (resourceId === undefined || resourceId === null) {
        throw new Error("Missing the required parameter 'resourceId' when calling egressTrunkResourceIdPatch");
      }


      var pathParams = {
        'resource_id': resourceId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20022;

      return this.apiClient.callApi(
        '/egress_trunk/{resource_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ingressTrunkResourceIdDelete operation.
     * @callback module:api/CarrierApi~ingressTrunkResourceIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Success} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes ingresstrunk
     * @param {Number} resourceId IngressTrunk id to get info about
     * @param {module:api/CarrierApi~ingressTrunkResourceIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Success}
     */
    this.ingressTrunkResourceIdDelete = function(resourceId, callback) {
      var postBody = null;

      // verify the required parameter 'resourceId' is set
      if (resourceId === undefined || resourceId === null) {
        throw new Error("Missing the required parameter 'resourceId' when calling ingressTrunkResourceIdDelete");
      }


      var pathParams = {
        'resource_id': resourceId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Success;

      return this.apiClient.callApi(
        '/ingress_trunk/{resource_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ingressTrunkResourceIdGet operation.
     * @callback module:api/CarrierApi~ingressTrunkResourceIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20024} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets ingresstrunk
     * @param {Number} resourceId IngressTrunk id to get info about
     * @param {module:api/CarrierApi~ingressTrunkResourceIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20024}
     */
    this.ingressTrunkResourceIdGet = function(resourceId, callback) {
      var postBody = null;

      // verify the required parameter 'resourceId' is set
      if (resourceId === undefined || resourceId === null) {
        throw new Error("Missing the required parameter 'resourceId' when calling ingressTrunkResourceIdGet");
      }


      var pathParams = {
        'resource_id': resourceId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20024;

      return this.apiClient.callApi(
        '/ingress_trunk/{resource_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ingressTrunkResourceIdPatch operation.
     * @callback module:api/CarrierApi~ingressTrunkResourceIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20024} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies ingresstrunk
     * @param {Number} resourceId IngressTrunk id to get info about
     * @param {Object} opts Optional parameters
     * @param {module:model/IngressTrunkModify} opts.body IngressTrunk to modify
     * @param {module:api/CarrierApi~ingressTrunkResourceIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20024}
     */
    this.ingressTrunkResourceIdPatch = function(resourceId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'resourceId' is set
      if (resourceId === undefined || resourceId === null) {
        throw new Error("Missing the required parameter 'resourceId' when calling ingressTrunkResourceIdPatch");
      }


      var pathParams = {
        'resource_id': resourceId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20024;

      return this.apiClient.callApi(
        '/ingress_trunk/{resource_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
