/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DnlApi);
  }
}(this, function(expect, DnlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DnlApi.AuthorizationLogGet();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthorizationLogGet', function() {
    it('should create an instance of AuthorizationLogGet', function() {
      // uncomment below and update the code to test AuthorizationLogGet
      //var instane = new DnlApi.AuthorizationLogGet();
      //expect(instance).to.be.a(DnlApi.AuthorizationLogGet);
    });

    it('should have the property loginIp (base name: "login_ip")', function() {
      // uncomment below and update the code to test the property loginIp
      //var instane = new DnlApi.AuthorizationLogGet();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new DnlApi.AuthorizationLogGet();
      //expect(instance).to.be();
    });

    it('should have the property failedReason (base name: "failed_reason")', function() {
      // uncomment below and update the code to test the property failedReason
      //var instane = new DnlApi.AuthorizationLogGet();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new DnlApi.AuthorizationLogGet();
      //expect(instance).to.be();
    });

    it('should have the property enteredPassword (base name: "entered_password")', function() {
      // uncomment below and update the code to test the property enteredPassword
      //var instane = new DnlApi.AuthorizationLogGet();
      //expect(instance).to.be();
    });

    it('should have the property loginTime (base name: "login_time")', function() {
      // uncomment below and update the code to test the property loginTime
      //var instane = new DnlApi.AuthorizationLogGet();
      //expect(instance).to.be();
    });

  });

}));
