/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DnlApi);
  }
}(this, function(expect, DnlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DnlApi.DidBillingPlanGet();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DidBillingPlanGet', function() {
    it('should create an instance of DidBillingPlanGet', function() {
      // uncomment below and update the code to test DidBillingPlanGet
      //var instane = new DnlApi.DidBillingPlanGet();
      //expect(instance).to.be.a(DnlApi.DidBillingPlanGet);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new DnlApi.DidBillingPlanGet();
      //expect(instance).to.be();
    });

    it('should have the property monthlyFee (base name: "monthly_fee")', function() {
      // uncomment below and update the code to test the property monthlyFee
      //var instane = new DnlApi.DidBillingPlanGet();
      //expect(instance).to.be();
    });

    it('should have the property rateTableName (base name: "rate_table_name")', function() {
      // uncomment below and update the code to test the property rateTableName
      //var instane = new DnlApi.DidBillingPlanGet();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DnlApi.DidBillingPlanGet();
      //expect(instance).to.be();
    });

    it('should have the property ratePerMin (base name: "rate_per_min")', function() {
      // uncomment below and update the code to test the property ratePerMin
      //var instane = new DnlApi.DidBillingPlanGet();
      //expect(instance).to.be();
    });

    it('should have the property rateTableId (base name: "rate_table_id")', function() {
      // uncomment below and update the code to test the property rateTableId
      //var instane = new DnlApi.DidBillingPlanGet();
      //expect(instance).to.be();
    });

    it('should have the property payphoneSubcharge (base name: "payphone_subcharge")', function() {
      // uncomment below and update the code to test the property payphoneSubcharge
      //var instane = new DnlApi.DidBillingPlanGet();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new DnlApi.DidBillingPlanGet();
      //expect(instance).to.be();
    });

    it('should have the property setupFee (base name: "setup_fee")', function() {
      // uncomment below and update the code to test the property setupFee
      //var instane = new DnlApi.DidBillingPlanGet();
      //expect(instance).to.be();
    });

  });

}));
