/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DnlApi);
  }
}(this, function(expect, DnlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DnlApi.DynamicRouteGet();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DynamicRouteGet', function() {
    it('should create an instance of DynamicRouteGet', function() {
      // uncomment below and update the code to test DynamicRouteGet
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be.a(DnlApi.DynamicRouteGet);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be();
    });

    it('should have the property routeRuleName (base name: "route_rule_name")', function() {
      // uncomment below and update the code to test the property routeRuleName
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be();
    });

    it('should have the property egressTrunks (base name: "egress_trunks")', function() {
      // uncomment below and update the code to test the property egressTrunks
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be();
    });

    it('should have the property dynamicRouteId (base name: "dynamic_route_id")', function() {
      // uncomment below and update the code to test the property dynamicRouteId
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be();
    });

    it('should have the property timeProfileId (base name: "time_profile_id")', function() {
      // uncomment below and update the code to test the property timeProfileId
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be();
    });

    it('should have the property timeProfile (base name: "time_profile")', function() {
      // uncomment below and update the code to test the property timeProfile
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be();
    });

    it('should have the property modifiedBy (base name: "modified_by")', function() {
      // uncomment below and update the code to test the property modifiedBy
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be();
    });

    it('should have the property qosCycle (base name: "qos_cycle")', function() {
      // uncomment below and update the code to test the property qosCycle
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be();
    });

    it('should have the property usageCount (base name: "usage_count")', function() {
      // uncomment below and update the code to test the property usageCount
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be();
    });

    it('should have the property lastModified (base name: "last_modified")', function() {
      // uncomment below and update the code to test the property lastModified
      //var instane = new DnlApi.DynamicRouteGet();
      //expect(instance).to.be();
    });

  });

}));
