/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DnlApi);
  }
}(this, function(expect, DnlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DnlApi.QosTotal();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QosTotal', function() {
    it('should create an instance of QosTotal', function() {
      // uncomment below and update the code to test QosTotal
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be.a(DnlApi.QosTotal);
    });

    it('should have the property call (base name: "call")', function() {
      // uncomment below and update the code to test the property call
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be();
    });

    it('should have the property cps (base name: "cps")', function() {
      // uncomment below and update the code to test the property cps
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be();
    });

    it('should have the property serverPort (base name: "server_port")', function() {
      // uncomment below and update the code to test the property serverPort
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be();
    });

    it('should have the property ingressCps (base name: "ingress_cps")', function() {
      // uncomment below and update the code to test the property ingressCps
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be();
    });

    it('should have the property egressChannels (base name: "egress_channels")', function() {
      // uncomment below and update the code to test the property egressChannels
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be();
    });

    it('should have the property egressCps (base name: "egress_cps")', function() {
      // uncomment below and update the code to test the property egressCps
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be();
    });

    it('should have the property ingressChannels (base name: "ingress_channels")', function() {
      // uncomment below and update the code to test the property ingressChannels
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be();
    });

    it('should have the property serverIp (base name: "server_ip")', function() {
      // uncomment below and update the code to test the property serverIp
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be();
    });

    it('should have the property reportTime (base name: "report_time")', function() {
      // uncomment below and update the code to test the property reportTime
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be();
    });

    it('should have the property channels (base name: "channels")', function() {
      // uncomment below and update the code to test the property channels
      //var instane = new DnlApi.QosTotal();
      //expect(instance).to.be();
    });

  });

}));
