/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DnlApi);
  }
}(this, function(expect, DnlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DnlApi.RateSendLogDetailGet();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RateSendLogDetailGet', function() {
    it('should create an instance of RateSendLogDetailGet', function() {
      // uncomment below and update the code to test RateSendLogDetailGet
      //var instane = new DnlApi.RateSendLogDetailGet();
      //expect(instance).to.be.a(DnlApi.RateSendLogDetailGet);
    });

    it('should have the property sendTo (base name: "send_to")', function() {
      // uncomment below and update the code to test the property sendTo
      //var instane = new DnlApi.RateSendLogDetailGet();
      //expect(instance).to.be();
    });

    it('should have the property downloadDate (base name: "download_date")', function() {
      // uncomment below and update the code to test the property downloadDate
      //var instane = new DnlApi.RateSendLogDetailGet();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DnlApi.RateSendLogDetailGet();
      //expect(instance).to.be();
    });

    it('should have the property trunkId (base name: "trunk_id")', function() {
      // uncomment below and update the code to test the property trunkId
      //var instane = new DnlApi.RateSendLogDetailGet();
      //expect(instance).to.be();
    });

    it('should have the property sendOn (base name: "send_on")', function() {
      // uncomment below and update the code to test the property sendOn
      //var instane = new DnlApi.RateSendLogDetailGet();
      //expect(instance).to.be();
    });

    it('should have the property parentJob (base name: "parent_job")', function() {
      // uncomment below and update the code to test the property parentJob
      //var instane = new DnlApi.RateSendLogDetailGet();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new DnlApi.RateSendLogDetailGet();
      //expect(instance).to.be();
    });

  });

}));
