/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DnlApi);
  }
}(this, function(expect, DnlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DnlApi.ResourceReplaceActionGet();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResourceReplaceActionGet', function() {
    it('should create an instance of ResourceReplaceActionGet', function() {
      // uncomment below and update the code to test ResourceReplaceActionGet
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be.a(DnlApi.ResourceReplaceActionGet);
    });

    it('should have the property dnisMaxLength (base name: "dnis_max_length")', function() {
      // uncomment below and update the code to test the property dnisMaxLength
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

    it('should have the property dnis (base name: "dnis")', function() {
      // uncomment below and update the code to test the property dnis
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

    it('should have the property dnisPrefix (base name: "dnis_prefix")', function() {
      // uncomment below and update the code to test the property dnisPrefix
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

    it('should have the property aniMinLength (base name: "ani_min_length")', function() {
      // uncomment below and update the code to test the property aniMinLength
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

    it('should have the property aniMaxLength (base name: "ani_max_length")', function() {
      // uncomment below and update the code to test the property aniMaxLength
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

    it('should have the property dnisMinLength (base name: "dnis_min_length")', function() {
      // uncomment below and update the code to test the property dnisMinLength
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

    it('should have the property resourceId (base name: "resource_id")', function() {
      // uncomment below and update the code to test the property resourceId
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

    it('should have the property aniPrefix (base name: "ani_prefix")', function() {
      // uncomment below and update the code to test the property aniPrefix
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

    it('should have the property ani (base name: "ani")', function() {
      // uncomment below and update the code to test the property ani
      //var instane = new DnlApi.ResourceReplaceActionGet();
      //expect(instance).to.be();
    });

  });

}));
