/**
 * DNL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DnlApi);
  }
}(this, function(expect, DnlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DnlApi.SwitchProfileSipHostGet();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SwitchProfileSipHostGet', function() {
    it('should create an instance of SwitchProfileSipHostGet', function() {
      // uncomment below and update the code to test SwitchProfileSipHostGet
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be.a(DnlApi.SwitchProfileSipHostGet);
    });

    it('should have the property cps (base name: "cps")', function() {
      // uncomment below and update the code to test the property cps
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property cap (base name: "cap")', function() {
      // uncomment below and update the code to test the property cap
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property priv (base name: "priv")', function() {
      // uncomment below and update the code to test the property priv
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property rpid (base name: "rpid")', function() {
      // uncomment below and update the code to test the property rpid
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property xHeader (base name: "x_header")', function() {
      // uncomment below and update the code to test the property xHeader
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property xLrn (base name: "x_lrn")', function() {
      // uncomment below and update the code to test the property xLrn
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property sipIp (base name: "sip_ip")', function() {
      // uncomment below and update the code to test the property sipIp
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property switchId (base name: "switch_id")', function() {
      // uncomment below and update the code to test the property switchId
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property pci (base name: "pci")', function() {
      // uncomment below and update the code to test the property pci
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property div (base name: "div")', function() {
      // uncomment below and update the code to test the property div
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property paid (base name: "paid")', function() {
      // uncomment below and update the code to test the property paid
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property sipPort (base name: "sip_port")', function() {
      // uncomment below and update the code to test the property sipPort
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property supportRegister (base name: "support_register")', function() {
      // uncomment below and update the code to test the property supportRegister
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property oli (base name: "oli")', function() {
      // uncomment below and update the code to test the property oli
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

    it('should have the property hostName (base name: "host_name")', function() {
      // uncomment below and update the code to test the property hostName
      //var instane = new DnlApi.SwitchProfileSipHostGet();
      //expect(instance).to.be();
    });

  });

}));
